# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14f69658-c461-4369-86c7-fbff9f45fa1a";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };
  networking.hostName = "bear";
  boot.initrd.luks.devices = {
     "luks-f7676a85-d4ff-4960-bb83-3f5f7eff20d7".device = "/dev/disk/by-uuid/f7676a85-d4ff-4960-bb83-3f5f7eff20d7";
     "luks-8c0d564d-2893-4e17-bfe4-aa4c4b34a190".device = "/dev/disk/by-uuid/8c0d564d-2893-4e17-bfe4-aa4c4b34a190";
  };
  
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4828-D586";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

# Used to be /dev/disk/by-uuid/...
   swapDevices = 
    [ {
        device = "/dev/mapper/luks-8c0d564d-2893-4e17-bfe4-aa4c4b34a190";
	priority = 2;
       }
    ]; 
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
